### ISSUE TITLE
Add Nano dosages

### ISSUE THREAD

**Issue by Robert95z** [allenh1/reef_moonshiners#13]

**Comment by allenh1** [comment]
@Robert95z ah, good idea! I will certainly do so. Thanks!

**Comment by allenh1** [comment]
@Robert95z I've added nano dosage as an option!

![image](https://user-images.githubusercontent.com/2013091/190865186-101230e8-fe73-4fdb-8a13-183fd1a7a96e.png)

![image](https://user-images.githubusercontent.com/2013091/190865195-f237825e-6390-4a1c-aae4-43ca4ddde9c0.png)
